name: CI

on:
  push:
    branches: [ master ]
    paths:
      - content.md
      - template.html
  pull_request:
    branches: [ master ]
      - content.md
      - template.html


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
      - name: Checkout marked
        uses: actions/checkout@v3
        with:
          repository: aprotim/marked
          path: marked
          
      - name: install tidy
        run: sudo apt-get install tidy

      - name: Build html
        run: |
          sed '0,/^\s*<!--\s*Start content\s*-->/I!d' main/template.html > resume.html 
          ./marked/bin/marked -i ./main/content.md >> resume.html
          sed '/^\s*<!--\s*End content\s*-->/I,$!d' main/template.html >> resume.html
          tidy -q -i -m resume.html
          
      - name: Upload resume
        uses: actions/upload-artifact@v3
        with:
          name: resume
          path: resume.html
      
      - name: Commit resume
        run: |
          cp resume.html ./main/resume.html
          cd main
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add resume.html
          git commit -m "Update resume contents from commit $(git rev-parse --short "$GITHUB_SHA")"
          git push
          

 
